version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  web:
    build:
      context: ./apache_image
      dockerfile: Dockerfile
    ports:
      - "8080:80"
#    volumes:
#      - ./www:/var/www/html

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql # Инициализация дб, пользователя
      - ./mysql-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d # Директория с дампом базы (баловство, просто протестить)
    environment:
      MYSQL_ROOT_PASSWORD: "root"
